language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

install:
  - composer self-update
  - composer --version
  - composer global require "fxp/composer-asset-plugin:1.0.0"
  - composer require "yiisoft/yii2:@dev" --prefer-dist --no-interaction
  - composer install --prefer-dist --no-interaction
  - composer show -i

script:
  - vendor/bin/phpunit