language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

env:
  - YII2_VERSION=2.0.0
  - YII2_VERSION=2.0.1
  - YII2_VERSION=2.0.2
  - YII2_VERSION=2.0.3
  - YII2_VERSION=2.0.4
  - YII2_VERSION=@dev

install:
  - composer self-update
  - composer --version
  - composer global require "fxp/composer-asset-plugin:1.0.0"
  - composer require "yiisoft/yii2:$YII2_VERSION" --prefer-dist --no-interaction
  - composer install  --prefer-dist --no-interaction
  - composer show -i

script:
  - vendor/bin/phpunit